/**
 * Verified celebrity birth data for SEO chart pages.
 *
 * Each record was researched against Astro-Databank (Rodden rating) and
 * independently re-verified; only entries with a reliable, undisputed birth
 * time are included (others were held back rather than publish a wrong chart).
 * The chart is computed from this data at render time by worker/seo.js.
 */

export const CELEBRITIES = [
  {"slug":"albert-einstein","name":"Albert Einstein","birthDate":"1879-03-14","birthTime":"11:30","place":"Ulm, Baden-Wurttemberg, Germany","utcOffset":0.89,"rodden":"AA","source":"https://www.astro.com/astro-databank/Einstein,_Albert"},
  {"slug":"amy-winehouse","name":"Amy Winehouse","birthDate":"1983-09-14","birthTime":"22:25","place":"London, England, United Kingdom","utcOffset":1,"rodden":"A","source":"https://www.astro.com/astro-databank/Winehouse,_Amy"},
  {"slug":"angelina-jolie","name":"Angelina Jolie","birthDate":"1975-06-04","birthTime":"09:09","place":"Los Angeles, California, United States","utcOffset":-7,"rodden":"AA","source":"https://www.astro.com/astro-databank/Jolie,_Angelina"},
  {"slug":"audrey-hepburn","name":"Audrey Hepburn","birthDate":"1929-05-04","birthTime":"03:00","place":"Ixelles-Elsene, Brussels Capital, Belgium","utcOffset":1,"rodden":"AA","source":"Astro-Databank (astro.com/astro-databank/Hepburn,_Audrey) — AA rating, source De Marre, 03:00 Ixelles (confirmed via cached/search snippets; page itself bot-walled on direct fetch)"},
  {"slug":"barack-obama","name":"Barack Obama","birthDate":"1961-08-04","birthTime":"19:24","place":"Honolulu, Hawaii, United States","utcOffset":-10,"rodden":"AA","source":"https://www.astro.com/astro-databank/Obama,_Barack — Astro-Databank: 4 August 1961, 7:24 PM, Honolulu HI; Rodden AA. Source notes record the June 2008 upgrade from DD to AA when the 7:24 PM birth-certificate copy appeared (superseding the earlier 7:11 PM DD claim from Joni Patry at UAC Denver, May 2008)."},
  {"slug":"beyonce","name":"Beyoncé","birthDate":"1981-09-04","birthTime":"21:47","place":"Houston, Texas, United States","utcOffset":-5,"rodden":"AA","source":"https://www.astro.com/astro-databank/Beyonc%C3%A9 (Astro-Databank entry; secondary reporting indicates it is now rated AA from the birth certificate — page itself was behind a browser-check and could not be loaded directly)"},
  {"slug":"bob-dylan","name":"Bob Dylan","birthDate":"1941-05-24","birthTime":"21:05","place":"Duluth, Minnesota, United States","utcOffset":-5,"rodden":"AA","source":"https://www.astro.com/astro-databank/Dylan,_Bob (Astro-Databank — Rodden AA, 21:05, Duluth; page itself behind bot-check, values confirmed via mirrors below)"},
  {"slug":"david-bowie","name":"David Bowie","birthDate":"1947-01-08","birthTime":"09:00","place":"Brixton, England, United Kingdom","utcOffset":0,"rodden":"A","source":"Astro-Databank (astro.com/astro-databank/Bowie,_David) — David Bowie, 8 Jan 1947, 09:00 GMT, London; Rodden rating A. Time from Peter & Leni Gillman, 'Alias David Bowie' (1986), given as 9:00 AM GMT 'from his parents'; corroborated by Mary Angela Barnett's 'Backstage Passes'. Databank updated from older 9:15 AM to 9:00 AM in May 2015."},
  {"slug":"elon-musk","name":"Elon Musk","birthDate":"1971-06-28","birthTime":"07:30","place":"Pretoria, Gauteng, South Africa","utcOffset":2,"rodden":"B","source":"https://www.astro.com/astro-databank/Musk,_Elon"},
  {"slug":"elvis-presley","name":"Elvis Presley","birthDate":"1935-01-08","birthTime":"04:35","place":"Tupelo, Mississippi, United States","utcOffset":-6,"rodden":"AA","source":"Astro-Databank (astro.com): Presley, Elvis — 8 Jan 1935, 04:35 (CST), Tupelo MS; Rodden rating AA, source Sy Scholfield citing Dr. Robert Hunt's doctor's record"},
  {"slug":"frida-kahlo","name":"Frida Kahlo","birthDate":"1907-07-06","birthTime":"08:30","place":"Coyoacán, Mexico City, Mexico","utcOffset":-6.61,"rodden":"AA","source":"https://www.astro.com/astro-databank/Kahlo,_Frida"},
  {"slug":"jimi-hendrix","name":"Jimi Hendrix","birthDate":"1942-11-27","birthTime":"10:15","place":"Seattle, Washington, United States","utcOffset":-7,"rodden":"AA","source":"https://www.astro.com/astro-databank/Hendrix,_Jimi (Astro-Databank — primary record, Rodden AA from birth certificate; direct fetch bot-blocked/browser-check, but rating and 10:15 AM time reproduced verbatim by the two mirrors below and by the search-engine summary of the Databank biography)"},
  {"slug":"john-f-kennedy","name":"John F. Kennedy","birthDate":"1917-05-29","birthTime":"15:00","place":"Brookline, Massachusetts, United States","utcOffset":-5,"rodden":"A","source":"https://www.astro.com/astro-databank/Kennedy,_John_F. (Astro-Databank: 29 May 1917, 15:00, Brookline MA; Rodden Rating A; time credited to multiple corroborating sources)"},
  {"slug":"kurt-cobain","name":"Kurt Cobain","birthDate":"1967-02-20","birthTime":"19:38","place":"Aberdeen, Washington, United States","utcOffset":-8,"rodden":"AA","source":"https://astro-charts.com/persons/chart/kurt-cobain/"},
  {"slug":"leonardo-dicaprio","name":"Leonardo DiCaprio","birthDate":"1974-11-11","birthTime":"02:47","place":"Los Angeles, California, United States","utcOffset":-8,"rodden":"AA","source":"https://www.astro.com/astro-databank/DiCaprio,_Leonardo"},
  {"slug":"madonna","name":"Madonna","birthDate":"1958-08-16","birthTime":"07:05","place":"Bay City, Michigan, United States","utcOffset":-5,"rodden":"A","source":"https://www.astro.com/astro-databank/Madonna"},
  {"slug":"marilyn-monroe","name":"Marilyn Monroe","birthDate":"1926-06-01","birthTime":"09:30","place":"Los Angeles, California, United States","utcOffset":-8,"rodden":"AA","source":"https://en.wikipedia.org/wiki/Marilyn_Monroe (born Norma Jeane Mortenson, June 1 1926, Los Angeles General Hospital, Boyle Heights - date/place confirmed directly)"},
  {"slug":"marlon-brando","name":"Marlon Brando","birthDate":"1924-04-03","birthTime":"23:00","place":"Omaha, Nebraska, United States","utcOffset":-6,"rodden":"AA","source":"https://www.astro.com/astro-databank/Brando,_Marlon (Astro-Databank: 3 April 1924, 23:00, Omaha NE, Rodden AA; source Doane quotes B.C. / Gauquelin Book of American Charts)"},
  {"slug":"meryl-streep","name":"Meryl Streep","birthDate":"1949-06-22","birthTime":"08:05","place":"Summit, New Jersey, United States","utcOffset":-4,"rodden":"AA","source":"https://www.astro.com/astro-databank/Streep,_Meryl"},
  {"slug":"nikola-tesla","name":"Nikola Tesla","birthDate":"1856-07-10","birthTime":"00:00","place":"Smiljan, Lika-Senj County, Croatia","utcOffset":1.37,"rodden":"B","source":"https://www.astro.com/astro-databank/Tesla,_Nikola"},
  {"slug":"oprah-winfrey","name":"Oprah Winfrey","birthDate":"1954-01-29","birthTime":"04:30","place":"Kosciusko, Mississippi, United States","utcOffset":-6,"rodden":"A","source":"https://www.astro.com/astro-databank/Winfrey,_Oprah"},
  {"slug":"prince","name":"Prince","birthDate":"1958-06-07","birthTime":"18:17","place":"Minneapolis, Minnesota, United States","utcOffset":-5,"rodden":"AA","source":"https://www.astrotheme.com/astrology/Prince_(musician) — Astrotheme: 7 June 1958, 6:17 PM, Minneapolis MN, USA; reliability rating AA ('birth certificate or birth record'), contributor Frank C. Clifford. Directly fetched and confirmed."},
  {"slug":"robin-williams","name":"Robin Williams","birthDate":"1951-07-21","birthTime":"13:34","place":"Chicago, Illinois, United States","utcOffset":-5,"rodden":"AA","source":"https://www.astro.com/astro-databank/Williams,_Robin"},
  {"slug":"sigmund-freud","name":"Sigmund Freud","birthDate":"1856-05-06","birthTime":"18:30","place":"Příbor, Moravian-Silesian Region, Czechia","utcOffset":0.96,"rodden":"AA","source":"https://www.astro.com/astro-databank/Freud,_Sigmund"},
  {"slug":"steve-jobs","name":"Steve Jobs","birthDate":"1955-02-24","birthTime":"19:15","place":"San Francisco, California, United States","utcOffset":-8,"rodden":"AA","source":"https://www.astro.com/astro-databank/Jobs,_Steve"},
  {"slug":"whitney-houston","name":"Whitney Houston","birthDate":"1963-08-09","birthTime":"20:55","place":"Newark, New Jersey, United States","utcOffset":-4,"rodden":"AA","source":"https://www.astro.com/astro-databank/Houston,_Whitney"}
];
